In [1]:
import pandas as pd
import json
import numpy as np

In [23]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [24]:
sinllama_drift_report = pd.read_csv("../Data/SinLlama_lemma_drift_analysis.csv")
xlmr_drift_report = pd.read_csv("../Data/XLM-R_lemma_drift_analysis.csv")

In [26]:
sinllama_drift_report.head()

      lemma permutation  anchor_century  target_century direction  global_distance  persistent_shift  drift_reduction_pct  innovation_count  total_instance_count  \
0    බැවින්       13_14              13              14   Forward         0.230417          0.230417             0.000000                 0                     1
1        ලො       13_14              13              14   Forward         0.109623          0.093474            14.731328                 2                    10
2       එක්       13_14              13              14   Forward         0.148147          0.148147             0.000000                 0                     2
3    පිරිවර       13_14              13              14   Forward         0.089760          0.080884             9.888487                 3                     7
4  ක්රමයෙන්       13_14              13              14   Forward         0.081211          0.063830            21.401934                 3                     9

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              informer_data
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        []
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           [('අසරණ සරණ වූ සරණාගත වජ්රපඤජර වූ කරුණා නිධාන වූ තුන් ලොවට නායක වූ සම්යක් සම්බුද්ධ සර්වඥ රාජෝත්තමයානන් වහන්සේට උත්තමාදර ඇතියෙන් භකති ප්රෙමාති භාරාවනතො ත්ත මාර්ගයෙන් භය ලොභ කුලාචා රාදීන් වීනා සකසා වැඳ අර්ථ කථා නය ගෙන බුද්ධවංසය හෙවත් බුදුන් ගේ ජීවිත කථාව සිංහළ භාෂාවෙන් රචනා කරන්නෙමි', np.float32(0.010119319)), ('යම් හෙයකින් සත්වයන් සංසාර සාගර යෙන් එතර කිරීම් අර්ථ කොට ඇත්තා වූ තුන් ලොවට නායක වූ සර්වඥයන් වහන්සේ අනන්ත වූ යම් බොධි සම්භාරයක් පරිපාචනයකළේද', np.float32(0.008081913))]

In [4]:
sin_keys = sinllama_drift_report['lemma'].unique().tolist()
xlm_keys = xlmr_drift_report['lemma'].unique().tolist()

In [5]:
len(sinllama_drift_report), len(xlmr_drift_report)

(7830, 7830)

In [6]:
sinllama_drift_report['innovation_count'].sum(), sinllama_drift_report['total_instance_count'].sum()

(np.int64(24036), np.int64(112945))

In [7]:
xlmr_drift_report['direction'].value_counts()

direction
Forward    3915
Reverse    3915
Name: count, dtype: int64

In [15]:
xlmr_info = {'Avg Global Distance': xlmr_drift_report['global_distance'].mean(),
             'Avg Persistent Shift': xlmr_drift_report['persistent_shift'].mean(),
             'Avg Drift Reduction %': xlmr_drift_report['drift_reduction_pct'].mean(),
             'Drifted Instances': xlmr_drift_report['innovation_count'].sum(),
             'Total Instances': xlmr_drift_report['total_instance_count'].sum()}

In [16]:
sinllama_info = {'Avg Global Distance': sinllama_drift_report['global_distance'].mean(),
             'Avg Persistent Shift': sinllama_drift_report['persistent_shift'].mean(),
             'Avg Drift Reduction %': sinllama_drift_report['drift_reduction_pct'].mean(),
             'Drifted Instances': sinllama_drift_report['innovation_count'].sum(),
             'Total Instances': sinllama_drift_report['total_instance_count'].sum()}

In [28]:
sinllama_drift_report['global_distance'].mean()/xlmr_drift_report['global_distance'].mean()

np.float64(53.578742248306824)

In [17]:
df_drift = pd.DataFrame([xlmr_info, sinllama_info], index=['XLM-R', 'SinLlama'])

# 4. Clean up formatting (optional but recommended for mixed metrics)
# This keeps 4 decimal places for the averages but integers for counts
format_mapping = {
    'Avg Global Distance': '{:.2f}',
    'Avg Persistent Shift': '{:.2f}',
    'Avg Drift Reduction %': '{:.2f}%',
    'Drifted Instances': '{:,.0f}',
    'Total Instances': '{:,.0f}',
    'Total': '{:.2f}'
}

# Apply formatting for display
print(df_drift.style.format(format_mapping))

<pandas.io.formats.style.Styler object at 0x10bfb5610>

In [18]:
df_drift

,Avg Global Distance,Avg Persistent Shift,Avg Drift Reduction %,Drifted Instances,Total Instances
XLM-R,0.003513,0.003178,12.598977,22727,112945
SinLlama,0.188228,0.178176,7.091245,24036,112945

In [12]:
df_drift.to_latex('../Data/contextual_drift_report.tex', float_format="%.4f", index=True)

In [31]:
sinllama_drift_report = sinllama_drift_report.sort_values('drift_reduction_pct', ascending=False)

In [33]:
sinllama_drift_report.head(2)

,lemma,permutation,anchor_century,target_century,direction,global_distance,persistent_shift,drift_reduction_pct,innovation_count,total_instance_count,informer_data
4654,කෙසේද,18_15,18,15,Reverse,0.126210,0.000000,100.000000,1,2,"[('සුලකළ අන්ය ලකෘත වූ හෙළ රුවනින් ස්ඵටික පලිඟු මාණික්යයෙන් කළ කරණ ලද්දා වූ තුඟු උස් වූ නැබල මහත් වූලෙල සිලිලෙන් ලීලොපෙත ජලයෙන් පිරි සම්පූර්ණ වූ පිරිවෙන නැදුල පරිඛා සමීපයෙහි දිලියෙන්නා වූ පවුර ප්රාකාර තාප්ප ය කෙසේද කිරණාව ක්ෂීරාණිවය අලලනවර ආලොලනය කරණ කල්හි මත්පහර බල මථන කලඹන්නා වූ ප්රහාර බලයෙන් වට හාත්පස්හි සළාදී ඡෂ්ටා දානය කොට හෙවත් දියසුලි සෑදෙමින්නැඟි නැංගා වූ තරඟවැල තරංගාවලිය පළ කෙළේ ප්රකාශ කෙළේය෴', np.float32(0.12620991))]"
1918,තවද,14_18,14,18,Forward,0.265427,0.000047,99.982353,2,3,"[('මෙසෙයින් සම්ප්රමාණ වූ කාය ව්යාම ඇති න්යග්රොධ පරිමණ්ඩල ලක්ෂණයෙන් හා බුදුන්ගේ ග්රීවය සමග වටව රන් කලස කර සෙයින් ද රන් මිහිඟු බෙරික් සෙයින් වට වූ ග්රීවය ඇති සම වෘත්තස්ඛන්ධ ලක්ෂණයෙන් හ තවද බුදුන්ගේ සත්සියයක් ඊ සහරණිහු ඌර්ධවාග්රව ශ්රී ව යෙහිම පිහිටියා වු රසාග්ර සාග්ර ලක්ෂණයෙන්හා', np.float32(0.100037634)), ('යටහනුයෙහි දල්විස්සෙකැයි සතළිස් දත් ඇති චත්තාරිංශත් දන්ත ලක්ෂණයෙන් හා තවද යපතින් සිඳුනා ලද සක්පතක් සෙයින් සම වූ සමදන්ත ලක්ෂණ යෙන්හා පබලු පතෙක්හි හිඳු වූ විදුරු පෙලක් සේ ද තෙලි තුඬින් දක්වන ලද පරිච්ඡෙද බදු අවිවරදන්ත ලක්ෂණයෙන් හාස්ස මනාව සුදුවූ දෘෂ්ට්රා දහ වත්තරු අභිභවා දිලියෙන ප්රභාවෙන් අති ධවල වූ දෘෂ්ට ඇති සුසුලදාඨා ලක්ෂණයෙන් හා මෙලෙක් වූ දික් වූ පලල් වූ වර්ණ සම්පන්ත වූ මෙසෙයින් ත්රිලක්ෂණ සම්පන්න දිව් ඇති පහුතජික්වා ලක්ෂණයෙන් හා මහාබ්රහ්මයාගේ ස්වරයට බඳු වූ ගම්භීර ස්වරයෙන් යුක්ත වූ කුරවි කෙවිල්ලන් හඬ සෙයින් මිහිරි වූ ස්වර ඇති බ්රහ්ම ස්වර කරවීක භාණි ලක්ෂණයෙන් හා නිල් වුවමනා තන්හි දිය බෙරලිය මල් බඳු නිල් පැහැය රන්වන් වුවමනා තන්හි කිණිහිරි මල් බඳු වූ රන්වන් පැහැය සුදු වුවමනා තන්හී දහවත්තරු බඳු වූ ඉතා සුදු පැහැය කළු වුවමනාතන්හි රුක් පෙනල ඇට බඳු වූ ඉතා කළු පැහැය ඇති අභිනීල නෙත්ර ලක්ෂණයෙන් හාස්ස එවිගස උපන් රතුවස්සකුගේ අක්ෂිගුලිකා සෙයි ද ගුද්ධ කොට මැද තුබූ නිල්මැණික් ගුලිකා දෙකක් සෙයින් මෙලෙක් වූ සිනිඳු වූ නිල් අක්ෂි ගුල ඇති ගොපක්ෂම ලක්ෂණයෙන් හා බුදුන් ගේ නලල්තලමැද රන් පුවරුවක් මැද තුබූ රිදීබුබුලක්සේද තරුණාරුණ ප්රභානුරඤ්ජිත ගගණ තල මධ්යගත ඖෂධී තාරකාවක් සේ ද අතිසයින් දීප්තිමත්ව බබලන්නා වූ ඌණි රොම ලක්ෂණ යෙන් හා බුදුන්ගේ දකුණු කන්සිල පටගෙණ මාංශ පටල යෙක් නැගී සියලු නලල වසා පුරාගොස් වම් කන්සීල පැහැර සිටියා වූ දෘෂ්ණීෂ පෂ්ට බද්ධ ශීර්ෂය මෙන් ද උෂ්ණීෂයක් මෙන් හැම තන්හි පරිමණ්ඩල දිය බුබුලක් සෙයින් පරිපූර්ණ ශිර්ෂ ඇති උෂ්ණීෂ ශීර්ෂ ලක්ෂණයෙන් හා මෙසෙයින් අනූනාධික ද්වාත්රිංශත් වර මහා පුරුෂ ලක්ෂණයෙන් හාවිතානු පුර්වාංගුලි වටංගුලිතාදි අසූ අනුව්යංජන කේතුමාලා බ්යාම ප්රභානු රඤ්ජිත රූපකාය සම්පත්තීන්හා', np.float32(0.08457255))]"

In [36]:
sinllama_drift_report.iloc[1]

lemma                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    තවද
permutation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            14_18
anchor_century                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            14
target_century                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            18
direction                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Forward
global_distance                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0.265427
persistent_shift                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0.000047
drift_reduction_pct                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                99.982353
innovation_count                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           2
total_instance_count                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       3

In [44]:
sinllama_drift_report['lemma'].unique()

array(['කෙසේද', 'තවද', 'එසේ', 'මෙසේ', 'මී', 'මෙහි', 'එයින්', 'ඉ', 'ලබ',
       'ඒ', 'එසේම', 'ව', 'හෙයින්', 'නුවර', 'පමණ', 'කුමක්', 'කිය', 'නම',
       'එක', 'ඇති', 'එ', 'යත්', 'වඳ', 'දහස', 'මේ', 'රාජ', 'ගුණ', 'බල',
       'කොට', 'සිත', 'පූර්ව', 'ය', 'යනාදී', 'නග', 'මෙ', 'එම', 'පෙර',
       'කරන්න', 'යම්', 'සර්වඥ', 'වෙන', 'ම', 'කර', 'දකි', 'ශ්ර', 'සත',
       'ධර්ම', 'නිසි', 'ඊ', 'අනෙක', 'විසින්', 'ජන', 'රන්', 'බුදු', 'බස',
       'ඔහු', 'දාන', 'පස', 'භාව', 'යුතු', 'තම', 'වන', 'නවත', 'චන්ද්රයා',
       'සියලු', 'අප', 'එක්', 'ඵල', 'කළ', 'පුරුෂ', 'තෙම', 'උ', 'හට', 'ද',
       'නාම', 'කන', 'දන', 'හි', 'රැස', 'මතු', 'කටයුතු', 'අර්ථ', 'බව',
       'වඩ', 'සිටි', 'දෙ', 'උපද', 'යට', 'පද', 'බුද්ධ', 'මහ', 'අග්ර', 'සද',
       'යයි', 'පිණිස', 'ගෙණ', 'ප්රථම', 'සමග', 'තන්හි', 'බුදුන්', 'හා',
       'මඩ', 'ර', 'දිව්', 'අක්ෂර', 'උතුම්', 'සත්ව', 'රජ', 'දන්', 'සතර',
       'පි', 'පටන්', 'ගත', 'හිස', 'කෙළි', 'හ', 'කිරි', 'කල්හි', 'ලද',
       'ලක්ෂ', 'දක්වා', 'කිරීම', 'සාගර', 'උපන්', 'න', 'පමුණ', 'හර', 'අස',
       'වස', 'පැමිණි', 'කරණ', 'ආදි', 'කිසි', 'යොද', 'ලො', 'කවර', 'මෙන්',
       'ගොස', 'වහන්සේ', 'දෙදෙන', 'දෙන', 'පිට', 'දෙක', 'දුක', 'පළ',
       'ස්ථාන', 'මාර්ග', 'ක', 'මංගල', 'ගන්', 'කෙන', 'ල', 'අතුර', 'රූප',
       'පවත්ව', 'ලද්ද', 'කෙරෙන්', 'ශරීර', 'හෝ', 'ධාතු', 'ආදී', 'යුක්ත',
       'වනාහි', 'පාද', 'ගේ', 'බැවින්', 'නැති', 'සහිත', 'කල', 'බවට', 'සේ',
       'සමූහ', 'ආ', 'ප්රීති', 'ප්රධාන', 'තිබෙ', 'ඥාන', 'කාල', 'ක්රමයෙන්',
       'සංඛ්යාත', 'වර', 'ප්රකාශ', 'භාෂා', 'දෙස', 'කල්ප', 'පුර', 'ගෙ',
       'ප්රකාර', 'හෙවත්', 'මල', 'ප', 'වට', 'වශ', 'විශෙෂ', 'වි', 'කර්ම',
       'සුදුසු', 'කඳ', 'බ්රහ්ම', 'අන්ය', 'වංශ', 'සකල', 'පිහිට', 'ස',
       'සම්', 'කෙණ', 'කුමාර', 'වන්නේ', 'සඳහා', 'අත', 'පණ්ඩිත', 'වීම',
       'ප්රකරණ', 'සැප', 'දෙවි', 'ලෝක', 'නමැති', 'ඇත්තේ', 'වැසි', 'ලොක',
       'සම්පූර්ණ', 'සර්ව', 'කරව', 'මිනිස', 'දවස', 'දොෂ', 'ඇස', 'වසන', 'ණ',
       'නොද', 'මනුෂ්', 'ඇතිව', 'විසිනුද', 'තල', 'පිරිවර', 'අව', 'කා',
       'විමස', 'අන්ධකාර', 'රට', 'නොයෙක්', 'නැ', 'කරුණා', 'සියල්ල', 'නා',
       'මාර', 'විවරණ', 'දම', 'උපදි', 'පුද', 'වර්ධන', 'යෙහි', 'පරිද්දෙන්',
       'ලංකාද්වීප', 'සසර', 'සද්ධර්ම', 'පා', 'යහපත', 'පංච', 'ජාත',
       'සම්පුර්ණ'], dtype=object)

In [45]:
sinllama_drift_report[sinllama_drift_report['lemma'] == 'පංච']

,lemma,permutation,anchor_century,target_century,direction,global_distance,persistent_shift,drift_reduction_pct,innovation_count,total_instance_count,informer_data
3629,පංච,15_19,15,19,Forward,0.211893,0.205894,2.831072,2,5,"[('සම්බොධි ලක්ෂ්මි ලතා ලිංගිත කල්ප පාදපාය මානවූ අපගේ ගෞතම සම්මා සම්බුදුරජාණන් වහන්සේ මෙයින් සාරාසංඛ්ය කල්ප ලක්ෂයකින් අතීතයෙහි මොහාන්ධකාර විද්වංසනෛක ප්රදීපායමාන වූ දීපංකර බුදුරජාණන් වහන්සේගේ ශ්රීපාද මූලයෙහි දී විවරණ ශ්රී ලදින් සසර සැරිසරන්නාහු අනන්තා පරිමාණ කාලයක් ඇස් ඉස් මස් තුනුලේ හිරා දන් දී සමත්රිංශත් පාරමී ධර්මයන් කුළුගන්වා අන්තයෙහි විශ්වන්තරාත්ම භාවයෙහි සිට දෙරණ අහස් සයුරු සත් කුළ පව් මහමෙර ආදි වූ අචෛතනික වස්තූන් පවා දාන විෂයෙහි ප්රශංසා කරන්නවුන් මෙන් වෙවුල්වා තුෂිත භවනයෙහි ඉපිද අපමණ සැපත් විඳිමින් දස දහසක් සක්වළ දිව්ය බ්රහ්මයන්ගේ ආරාධනාවෙන් පංච මහා විලොකනය කොට ශාක්ය කූලාම්බර චන්ද්රරෙඛායමාණ විශිෂ්ට රූප ලාවණ්ය ශ්රීන් විරාජමාන වූ මහාමායා දේවීන් කුස පිළිසිඳ භ්රමරගණ විචුම්බිත ලුම්බිනි වනොද්යානයෙහිදී ප්රසුතව ක්රමයෙන් වැඩී රජ සිරි පැමිණ උයන් කෙළියට නික්ම සතර පූර්ව නිමිති දැක ගිහිගෙහි කලකිරී', np.float32(0.008373201)), ('සර්වඥයන් වහන්සේ එම පත්කඩ හැකුලු වූ කල දෙවියෝ සර්වඥයන් වහන්සේ කරා එලඹුනාහුය ඒ සමාගමයෙහි දී තථාගතයන් වහන්සේ දෙවියන්ට දහම් දෙසූ සේක අනේක කෝටි සංඛ්යාත සත්වයන්ට සෝවාන් ඵල අවබෝධ විය තිසරණ සහිත පංච ශීලයෙහි පිහිටිය වුන්ගේ සංඛ්යාව ගණන පථාතික්රාන්ත විය සමත්කුළුපව් වැසි මහා සුමන නම් දෙව් රජ තෙමේ ද සෝවාන් ඵලයට පැමිණියේ පූජාර්ග වූ සර්වඥයන් වහන්සේ කරා එළඹ පිදිය යුතු දෙයක් ඉල්විය සත්වයන් කෙරෙහි හිත වූ නිල වර්ණාන්විත සුපරිශුද්ධ කෙශවත් වූ සර්වඥයන් වහන්සේ ස්වකීය ශීර්ෂය පරාමර්ශනය කොට කෙශ ධාතු මිටක් පමණ ගෙන ප්රදානය කළ සේක ඉක්බිත්තෙන් හෙතෙම එය රන් සුමුගයකින් පිළිගත්තේ තථාගතයන් වහන්සේ වැඩහුන් ස්ථානයෙහි කරන ලද උස ප්රමාණයෙන් සත් රියන් වූ හාත්පස විසිඑක් රියන් සමාන වූ නන් වැදෑරුම් රුවන් රැසෙක්හි බහා ඉදුනිල්මය වූ චෛත්යයක් කොට පූර්වොක්ත කෙශ ධාතුව එහි නිධාන ගත කොට එම දෙව් රජ තෙමේ නමස්කාර කෙළේය', np.float32(0.0047504306))]"
1019,පංච,13_19,13,19,Forward,0.234225,0.228946,2.253788,2,5,"[('සර්වඥයන් වහන්සේ එම පත්කඩ හැකුලු වූ කල දෙවියෝ සර්වඥයන් වහන්සේ කරා එලඹුනාහුය ඒ සමාගමයෙහි දී තථාගතයන් වහන්සේ දෙවියන්ට දහම් දෙසූ සේක අනේක කෝටි සංඛ්යාත සත්වයන්ට සෝවාන් ඵල අවබෝධ විය තිසරණ සහිත පංච ශීලයෙහි පිහිටිය වුන්ගේ සංඛ්යාව ගණන පථාතික්රාන්ත විය සමත්කුළුපව් වැසි මහා සුමන නම් දෙව් රජ තෙමේ ද සෝවාන් ඵලයට පැමිණියේ පූජාර්ග වූ සර්වඥයන් වහන්සේ කරා එළඹ පිදිය යුතු දෙයක් ඉල්විය සත්වයන් කෙරෙහි හිත වූ නිල වර්ණාන්විත සුපරිශුද්ධ කෙශවත් වූ සර්වඥයන් වහන්සේ ස්වකීය ශීර්ෂය පරාමර්ශනය කොට කෙශ ධාතු මිටක් පමණ ගෙන ප්රදානය කළ සේක ඉක්බිත්තෙන් හෙතෙම එය රන් සුමුගයකින් පිළිගත්තේ තථාගතයන් වහන්සේ වැඩහුන් ස්ථානයෙහි කරන ලද උස ප්රමාණයෙන් සත් රියන් වූ හාත්පස විසිඑක් රියන් සමාන වූ නන් වැදෑරුම් රුවන් රැසෙක්හි බහා ඉදුනිල්මය වූ චෛත්යයක් කොට පූර්වොක්ත කෙශ ධාතුව එහි නිධාන ගත කොට එම දෙව් රජ තෙමේ නමස්කාර කෙළේය', np.float32(0.007991254)), ('සම්බොධි ලක්ෂ්මි ලතා ලිංගිත කල්ප පාදපාය මානවූ අපගේ ගෞතම සම්මා සම්බුදුරජාණන් වහන්සේ මෙයින් සාරාසංඛ්ය කල්ප ලක්ෂයකින් අතීතයෙහි මොහාන්ධකාර විද්වංසනෛක ප්රදීපායමාන වූ දීපංකර බුදුරජාණන් වහන්සේගේ ශ්රීපාද මූලයෙහි දී විවරණ ශ්රී ලදින් සසර සැරිසරන්නාහු අනන්තා පරිමාණ කාලයක් ඇස් ඉස් මස් තුනුලේ හිරා දන් දී සමත්රිංශත් පාරමී ධර්මයන් කුළුගන්වා අන්තයෙහි විශ්වන්තරාත්ම භාවයෙහි සිට දෙරණ අහස් සයුරු සත් කුළ පව් මහමෙර ආදි වූ අචෛතනික වස්තූන් පවා දාන විෂයෙහි ප්රශංසා කරන්නවුන් මෙන් වෙවුල්වා තුෂිත භවනයෙහි ඉපිද අපමණ සැපත් විඳිමින් දස දහසක් සක්වළ දිව්ය බ්රහ්මයන්ගේ ආරාධනාවෙන් පංච මහා විලොකනය කොට ශාක්ය කූලාම්බර චන්ද්රරෙඛායමාණ විශිෂ්ට රූප ලාවණ්ය ශ්රීන් විරාජමාන වූ මහාමායා දේවීන් කුස පිළිසිඳ භ්රමරගණ විචුම්බිත ලුම්බිනි වනොද්යානයෙහිදී ප්රසුතව ක්රමයෙන් වැඩී රජ සිරි පැමිණ උයන් කෙළියට නික්ම සතර පූර්ව නිමිති දැක ගිහිගෙහි කලකිරී', np.float32(0.004365802))]"
3107,පංච,15_14,15,14,Reverse,0.206874,0.203079,1.834148,1,2,"[('මේ ආදී අනෙකොපමාවෙන් ගිහිගෙන් නික්මෙන්නට සුදුසු අර්ථ සිතින් සලකා තමන්ගේ ප්රමානාතික්රාන්ත වූ ධන රාශිය යට කී ක්රමයෙන් යාචකාදීන්ට දන්දී වස්තු කාම ක්ලේශ කාමය හැර අමරණම් නුවරින් නික්ම හුදකලාව හිමවත ධර්මක නම් පර්වතය නිසා පංච දොෂ විනිර්මුක්ත පන්සලක් හා සක්මන්මළුවක් මවා කාමච්ඡන්දාදී පංචනීවරණ ධර්මයෙන් වෙන් වූ පංචාභිඥා අෂ්ට සමාපත්ති උපදවනු පිනිස ඒ ආශ්රම ප්රදෙශයෙහි නවදොෂ සමන්නාගත වූ සාටක යුගලය හැර ද්වාදශ ගුණ සමන්නාගත වූවාක් චීවරය හැඳ සෘෂි ප්රව්රජ්යාවෙන් පැවිදි වූ සේක෴', np.float32(0.003794372))]"
4934,පංච,18_19,18,19,Forward,0.197598,0.195193,1.217081,1,5,"[('බුදුන් වදාළ පංච ස්කන්ධ ධර්මකොට්ඨාසය ඉතා ගැඹුරුය', np.float32(0.0024049282))]"
7805,පංච,20_19,20,19,Reverse,0.195934,0.194408,0.779014,1,5,"[('සර්වඥයන් වහන්සේ එම පත්කඩ හැකුලු වූ කල දෙවියෝ සර්වඥයන් වහන්සේ කරා එලඹුනාහුය ඒ සමාගමයෙහි දී තථාගතයන් වහන්සේ දෙවියන්ට දහම් දෙසූ සේක අනේක කෝටි සංඛ්යාත සත්වයන්ට සෝවාන් ඵල අවබෝධ විය තිසරණ සහිත පංච ශීලයෙහි පිහිටිය වුන්ගේ සංඛ්යාව ගණන පථාතික්රාන්ත විය සමත්කුළුපව් වැසි මහා සුමන නම් දෙව් රජ තෙමේ ද සෝවාන් ඵලයට පැමිණියේ පූජාර්ග වූ සර්වඥයන් වහන්සේ කරා එළඹ පිදිය යුතු දෙයක් ඉල්විය සත්වයන් කෙරෙහි හිත වූ නිල වර්ණාන්විත සුපරිශුද්ධ කෙශවත් වූ සර්වඥයන් වහන්සේ ස්වකීය ශීර්ෂය පරාමර්ශනය කොට කෙශ ධාතු මිටක් පමණ ගෙන ප්රදානය කළ සේක ඉක්බිත්තෙන් හෙතෙම එය රන් සුමුගයකින් පිළිගත්තේ තථාගතයන් වහන්සේ වැඩහුන් ස්ථානයෙහි කරන ලද උස ප්රමාණයෙන් සත් රියන් වූ හාත්පස විසිඑක් රියන් සමාන වූ නන් වැදෑරුම් රුවන් රැසෙක්හි බහා ඉදුනිල්මය වූ චෛත්යයක් කොට පූර්වොක්ත කෙශ ධාතුව එහි නිධාන ගත කොට එම දෙව් රජ තෙමේ නමස්කාර කෙළේය', np.float32(0.0015263557))]"
758,පංච,13_18,13,18,Forward,0.256306,0.256306,0.000000,0,2,[]
7022,පංච,20_14,20,14,Reverse,0.130394,0.130394,0.000000,0,2,[]
7283,පංච,20_15,20,15,Reverse,0.266518,0.266518,0.000000,0,2,[]
6239,පංච,19_18,19,18,Reverse,0.197598,0.197598,0.000000,0,2,[]
7544,පංච,20_18,20,18,Reverse,0.253377,0.253377,0.000000,0,2,[]
497,පංච,13_15,13,15,Forward,0.326343,0.326343,0.000000,0,2,[]
6761,පංච,20_13,20,13,Reverse,0.262565,0.262565,0.000000,0,1,[]
6500,පංච,19_20,19,20,Forward,0.195934,0.195934,0.000000,0,1,[]
236,පංච,13_14,13,14,Forward,0.203791,0.203791,0.000000,0,2,[]
4151,පංච,18_13,18,13,Reverse,0.256306,0.256306,0.000000,0,1,[]
3890,පංච,15_20,15,20,Forward,0.266518,0.266518,0.000000,0,1,[]
2324,පංච,14_19,14,19,Forward,0.113947,0.113947,0.000000,0,5,[]
4412,පංච,18_14,18,14,Reverse,0.215762,0.215762,0.000000,0,2,[]
2063,පංච,14_18,14,18,Forward,0.215762,0.215762,0.000000,0,2,[]
2585,පංච,14_20,14,20,Forward,0.130394,0.130394,0.000000,0,1,[]
3368,පංච,15_18,15,18,Forward,0.360539,0.360539,0.000000,0,2,[]
2846,පංච,15_13,15,13,Reverse,0.326343,0.326343,0.000000,0,1,[]
1280,පංච,13_20,13,20,Forward,0.262565,0.262565,0.000000,0,1,[]
5717,පංච,19_14,19,14,Reverse,0.113947,0.113947,0.000000,0,2,[]
5456,පංච,19_13,19,13,Reverse,0.234225,0.234225,0.000000,0,1,[]
5978,පංච,19_15,19,15,Reverse,0.211893,0.211893,0.000000,0,2,[]
1802,පංච,14_15,14,15,Forward,0.206874,0.206874,0.000000,0,2,[]
4673,පංච,18_15,18,15,Reverse,0.360539,0.360539,0.000000,0,2,[]
5195,පංච,18_20,18,20,Forward,0.253377,0.253377,0.000000,0,1,[]
1541,පංච,14_13,14,13,Reverse,0.203791,0.203791,0.000000,0,1,[]