In [1]:
import pandas as pd
import json
import numpy as np

In [2]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_colwidth', None)

In [3]:
sinllama_drift_report = pd.read_csv("../Data/SinLlama_lemma_drift_analysis.csv")
xlmr_drift_report = pd.read_csv("../Data/XLM-R_lemma_drift_analysis_upd.csv")
llama_ft_drift_report = pd.read_csv("../Data/LlaMa_FT_lemma_drift_analysis_upd.csv")

In [4]:
sinllama_drift_report.head()

,lemma,permutation,anchor_century,target_century,direction,global_distance,persistent_shift,drift_reduction_pct,innovation_count,total_instance_count,informer_data
0,බැවින්,13_14,13,14,Forward,0.230417,0.230417,0.000000,0,1,[]
1,ලො,13_14,13,14,Forward,0.109623,0.093474,14.731328,2,10,[('අසරණ සරණ වූ සරණාගත වජ්රපඤජර වූ කරුණා නිධාන ...
2,එක්,13_14,13,14,Forward,0.148147,0.148147,0.000000,0,2,[]
3,පිරිවර,13_14,13,14,Forward,0.089760,0.080884,9.888487,3,7,[('එකල අජාසත් මහ රජාණෝ රජගහනුවර වේහාර පර්වත ප්...
4,ක්රමයෙන්,13_14,13,14,Forward,0.081211,0.063830,21.401934,3,9,[('එ සමයෙහි අවිද්යා නැමැති අන්ධකාරය නසන්නා සධර...

In [5]:
xlmr_drift_report.head()

,lemma,permutation,anchor_century,target_century,direction,global_distance,persistent_shift,drift_reduction_pct,innovation_count,total_instance_count,informer_data,anchor_sentences,target_sentences
0,කෙසේද,18_15,18,15,Reverse,0.001761,1.192093e-07,99.993225,1,2,[('සුලකළ අන්ය ලකෘත වූ හෙළ රුවනින් ස්ඵටික පලිඟු...,(හේ කෙසේද යත්),(හේ කෙසේද යත්) (සුලකළ අන්ය ලකෘත වූ හෙළ රුවනින්...
1,ම,14_13,14,13,Reverse,0.002965,7.443428e-04,74.893951,35,66,[('විසුද්ධි යයි සියලු රාගාදි මලයෙන් වෙන් වූ සර...,(ඔහුගේ දෙමවුපිය දෙදෙන ඔහුල දරු කාලයෙහි ම කාල ක...,(කණ හුණු දහම් අකුරෙන් අකුරකට අමාමහා නිවන් ම මි...
2,ලද්ද,18_14,18,14,Reverse,0.009036,2.305031e-03,74.491943,1,2,[('තවද මේ අනාගතවංශ දේශනාව කවරෙකු විසින් දෙසන ල...,(භගවත් අර්හත් සම්යක් සම්බුද්ධතාදි පිරිසිදු ගුණ...,(යනු හෙයින් නැවත අවුත් ඡන්න නම් ඇමැත්තහු පුබුද...
3,ආදි,20_13,20,13,Reverse,0.003974,1.034737e-03,73.959351,8,22,[('සලක ස්ථානයෙහි හෙවත් ගණය මුලුල්ලම ගුරු වුව හ...,(මේ රටේදී බල වැස්කි නමැතිනෝ ආදි මහත් තැන් විසි...,(යම් මෙ සතර මහ සීවටන් කෙනෙක් ඇද් ද සම්මප්පධානා...
4,යත්,18_15,18,15,Reverse,0.004249,1.143217e-03,73.097313,4,7,[('බියකරු සසර සසුරේ භයංකර සංසාර සාගරයෙහි බමණ භ...,(හේ කෙසේද යත්),(බියකරු සසර සසුරේ භයංකර සංසාර සාගරයෙහි බමණ භ්ර...

In [6]:
sin_keys = sinllama_drift_report['lemma'].unique().tolist()
xlm_keys = xlmr_drift_report['lemma'].unique().tolist()
llama_ft_keys = llama_ft_drift_report['lemma'].unique().tolist()

In [7]:
len(sinllama_drift_report), len(xlmr_drift_report), len(llama_ft_drift_report)

(7830, 5495, 5379)

In [8]:
sinllama_drift_report['innovation_count'].sum(), sinllama_drift_report['total_instance_count'].sum()

(np.int64(24036), np.int64(112945))

In [9]:
xlmr_drift_report['direction'].value_counts()

direction
Forward    2837
Reverse    2658
Name: count, dtype: int64

In [10]:
xlmr_info = {'Avg Global Distance': xlmr_drift_report['global_distance'].mean(),
             'Avg Persistent Shift': xlmr_drift_report['persistent_shift'].mean(),
             'Avg Drift Reduction %': xlmr_drift_report['drift_reduction_pct'].mean(),
             'Drifted Instances': xlmr_drift_report['innovation_count'].sum(),
             'Total Instances': xlmr_drift_report['total_instance_count'].sum()}

In [11]:
sinllama_info = {'Avg Global Distance': sinllama_drift_report['global_distance'].mean(),
             'Avg Persistent Shift': sinllama_drift_report['persistent_shift'].mean(),
             'Avg Drift Reduction %': sinllama_drift_report['drift_reduction_pct'].mean(),
             'Drifted Instances': sinllama_drift_report['innovation_count'].sum(),
             'Total Instances': sinllama_drift_report['total_instance_count'].sum()}

In [12]:
llama_info = {'Avg Global Distance': llama_ft_drift_report['global_distance'].mean(),
             'Avg Persistent Shift': llama_ft_drift_report['persistent_shift'].mean(),
             'Avg Drift Reduction %': llama_ft_drift_report['drift_reduction_pct'].mean(),
             'Drifted Instances': llama_ft_drift_report['innovation_count'].sum(),
             'Total Instances': llama_ft_drift_report['total_instance_count'].sum()}

In [13]:
sinllama_drift_report['global_distance'].mean()/xlmr_drift_report['global_distance'].mean()

np.float64(64.85215775865638)

In [14]:
df_drift = pd.DataFrame([xlmr_info, sinllama_info, llama_info], index=['XLM-R', 'SinLlama', 'LlaMa FT'])

# 4. Clean up formatting (optional but recommended for mixed metrics)
# This keeps 4 decimal places for the averages but integers for counts
format_mapping = {
    'Avg Global Distance': '{:.2f}',
    'Avg Persistent Shift': '{:.2f}',
    'Avg Drift Reduction %': '{:.2f}%',
    'Drifted Instances': '{:,.0f}',
    'Total Instances': '{:,.0f}',
    'Total': '{:.2f}'
}

# Apply formatting for display
print(df_drift.style.format(format_mapping))

<pandas.io.formats.style.Styler object at 0x169f8f8c0>

In [15]:
df_drift

,Avg Global Distance,Avg Persistent Shift,Avg Drift Reduction %,Drifted Instances,Total Instances
XLM-R,0.002902,0.002425,17.952683,22727,108334
SinLlama,0.188228,0.178176,7.091245,24036,112945
LlaMa FT,0.023632,0.020259,14.661680,21738,107855

In [16]:
result = llama_ft_drift_report.groupby('permutation').agg({
    'global_distance': 'mean',
    'persistent_shift': 'mean',
    'drift_reduction_pct': 'mean',
    'innovation_count': 'sum',
    'total_instance_count': 'sum'
}).reset_index()

# Optional: Rename columns for clarity
result = result.rename(columns={
    'global_distance': 'Avg Global Distance',
    'persistent_shift': 'Avg Persistent Shift',
    'drift_reduction_pct': 'Avg Drift Reduction %',
    'innovation_count': 'Drifted Instances',
    'total_instance_count': 'Total Instances'
})

In [17]:
result

,permutation,Avg Global Distance,Avg Persistent Shift,Avg Drift Reduction %,Drifted Instances,Total Instances
0,13_14,0.021939,0.017557,12.689333,394,1948
1,13_15,0.016481,0.013948,14.855829,509,2527
2,13_18,0.025874,0.021528,13.579997,381,1591
3,13_19,0.016866,0.014212,13.979439,849,4653
4,13_20,0.016445,0.013968,17.720106,1077,5842
5,14_13,0.025639,0.022008,16.567603,1004,4875
6,14_15,0.027728,0.023815,15.875374,580,2580
7,14_18,0.033075,0.027928,12.787321,439,1663
8,14_19,0.025960,0.021997,17.491053,973,4658
9,14_20,0.028066,0.024645,14.783242,1231,5880
10,15_13,0.018360,0.015825,15.887530,917,4835
11,15_14,0.026446,0.021981,6.984191,427,2001
12,15_18,0.026393,0.022487,14.567649,374,1642
13,15_19,0.022817,0.019086,16.348945,886,4709
14,15_20,0.019392,0.016825,14.876083,1092,5873
15,18_13,0.031135,0.027665,13.312530,906,4864
16,18_14,0.033446,0.029195,13.469220,436,2015
17,18_15,0.032623,0.028801,13.537203,570,2630
18,18_19,0.034000,0.029876,13.368317,926,4684
19,18_20,0.032413,0.029118,12.592726,1178,5872
20,19_13,0.017640,0.015187,16.509251,1000,4836
21,19_14,0.019543,0.016631,8.754851,436,1978
22,19_15,0.020130,0.017059,15.923192,514,2562
23,19_18,0.027544,0.023602,11.482679,393,1626
24,19_20,0.016304,0.013948,17.123393,986,5832
25,20_13,0.015782,0.013447,17.827630,983,4804
26,20_14,0.024928,0.020814,14.589777,450,2005
27,20_15,0.016117,0.013447,15.954558,580,2586
28,20_18,0.026476,0.022205,13.847282,408,1625
29,20_19,0.015397,0.012707,16.500767,839,4659

In [18]:
result.to_latex('../Data/llama_ft_contextual_drift_report.tex', float_format="%.4f", index=False)

In [19]:
df_drift

,Avg Global Distance,Avg Persistent Shift,Avg Drift Reduction %,Drifted Instances,Total Instances
XLM-R,0.002902,0.002425,17.952683,22727,108334
SinLlama,0.188228,0.178176,7.091245,24036,112945
LlaMa FT,0.023632,0.020259,14.661680,21738,107855

In [20]:
df_drift.to_latex('../Data/contextual_drift_report.tex', float_format="%.4f", index=True)

In [21]:
sinllama_drift_report = sinllama_drift_report.sort_values('drift_reduction_pct', ascending=False)

In [22]:
sinllama_drift_report.head(2)

,lemma,permutation,anchor_century,target_century,direction,global_distance,persistent_shift,drift_reduction_pct,innovation_count,total_instance_count,informer_data
4654,කෙසේද,18_15,18,15,Reverse,0.126210,0.000000,100.000000,1,2,[('සුලකළ අන්ය ලකෘත වූ හෙළ රුවනින් ස්ඵටික පලිඟු...
1918,තවද,14_18,14,18,Forward,0.265427,0.000047,99.982353,2,3,[('මෙසෙයින් සම්ප්රමාණ වූ කාය ව්යාම ඇති න්යග්රො...

In [23]:
sinllama_drift_report.iloc[1]

lemma                                                                 තවද
permutation                                                         14_18
anchor_century                                                         14
target_century                                                         18
direction                                                         Forward
global_distance                                                  0.265427
persistent_shift                                                 0.000047
drift_reduction_pct                                             99.982353
innovation_count                                                        2
total_instance_count                                                    3
informer_data           [('මෙසෙයින් සම්ප්රමාණ වූ කාය ව්යාම ඇති න්යග්රො...
Name: 1918, dtype: object

In [24]:
sinllama_drift_report['lemma'].unique()

<ArrowStringArray>
[    'කෙසේද',       'තවද',       'එසේ',      'මෙසේ',        'මී',      'මෙහි',
     'එයින්',         'ඉ',        'ලබ',         'ඒ',
 ...
      'යෙහි', 'පරිද්දෙන්', 'ලංකාද්වීප',       'සසර',   'සද්ධර්ම',        'පා',
      'යහපත',       'පංච',       'ජාත',  'සම්පුර්ණ']
Length: 261, dtype: str

In [25]:
sinllama_drift_report[sinllama_drift_report['lemma'] == 'පංච']

,lemma,permutation,anchor_century,target_century,direction,global_distance,persistent_shift,drift_reduction_pct,innovation_count,total_instance_count,informer_data
3629,පංච,15_19,15,19,Forward,0.211893,0.205894,2.831072,2,5,[('සම්බොධි ලක්ෂ්මි ලතා ලිංගිත කල්ප පාදපාය මානව...
1019,පංච,13_19,13,19,Forward,0.234225,0.228946,2.253788,2,5,[('සර්වඥයන් වහන්සේ එම පත්කඩ හැකුලු වූ කල දෙවිය...
3107,පංච,15_14,15,14,Reverse,0.206874,0.203079,1.834148,1,2,[('මේ ආදී අනෙකොපමාවෙන් ගිහිගෙන් නික්මෙන්නට සුද...
4934,පංච,18_19,18,19,Forward,0.197598,0.195193,1.217081,1,5,[('බුදුන් වදාළ පංච ස්කන්ධ ධර්මකොට්ඨාසය ඉතා ගැඹ...
7805,පංච,20_19,20,19,Reverse,0.195934,0.194408,0.779014,1,5,[('සර්වඥයන් වහන්සේ එම පත්කඩ හැකුලු වූ කල දෙවිය...
758,පංච,13_18,13,18,Forward,0.256306,0.256306,0.000000,0,2,[]
7022,පංච,20_14,20,14,Reverse,0.130394,0.130394,0.000000,0,2,[]
7283,පංච,20_15,20,15,Reverse,0.266518,0.266518,0.000000,0,2,[]
6239,පංච,19_18,19,18,Reverse,0.197598,0.197598,0.000000,0,2,[]
7544,පංච,20_18,20,18,Reverse,0.253377,0.253377,0.000000,0,2,[]
497,පංච,13_15,13,15,Forward,0.326343,0.326343,0.000000,0,2,[]
6761,පංච,20_13,20,13,Reverse,0.262565,0.262565,0.000000,0,1,[]
6500,පංච,19_20,19,20,Forward,0.195934,0.195934,0.000000,0,1,[]
236,පංච,13_14,13,14,Forward,0.203791,0.203791,0.000000,0,2,[]
4151,පංච,18_13,18,13,Reverse,0.256306,0.256306,0.000000,0,1,[]
3890,පංච,15_20,15,20,Forward,0.266518,0.266518,0.000000,0,1,[]
2324,පංච,14_19,14,19,Forward,0.113947,0.113947,0.000000,0,5,[]
4412,පංච,18_14,18,14,Reverse,0.215762,0.215762,0.000000,0,2,[]
2063,පංච,14_18,14,18,Forward,0.215762,0.215762,0.000000,0,2,[]
2585,පංච,14_20,14,20,Forward,0.130394,0.130394,0.000000,0,1,[]
3368,පංච,15_18,15,18,Forward,0.360539,0.360539,0.000000,0,2,[]
2846,පංච,15_13,15,13,Reverse,0.326343,0.326343,0.000000,0,1,[]
1280,පංච,13_20,13,20,Forward,0.262565,0.262565,0.000000,0,1,[]
5717,පංච,19_14,19,14,Reverse,0.113947,0.113947,0.000000,0,2,[]
5456,පංච,19_13,19,13,Reverse,0.234225,0.234225,0.000000,0,1,[]
5978,පංච,19_15,19,15,Reverse,0.211893,0.211893,0.000000,0,2,[]
1802,පංච,14_15,14,15,Forward,0.206874,0.206874,0.000000,0,2,[]
4673,පංච,18_15,18,15,Reverse,0.360539,0.360539,0.000000,0,2,[]
5195,පංච,18_20,18,20,Forward,0.253377,0.253377,0.000000,0,1,[]
1541,පංච,14_13,14,13,Reverse,0.203791,0.203791,0.000000,0,1,[]