In [1]:
import pandas as pd

In [40]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [2]:
sim_mat_report_wv = pd.read_csv("../Data/Word2Vec_dip_neighbors_similarity_matrix.csv")
analytical_op_report_wv = pd.read_csv("../Data/word2vec_dip_neighbors_orthogonal_procrustes.csv")
neural_op_report_wv = pd.read_csv("../Data/word2vec_dip_neighbors_orthogonal_procrustes_NN.csv")

sim_mat_report_ft = pd.read_csv("../Data/fasttext_dip_neighbors_similarity_matrix.csv")
analytical_op_report_ft = pd.read_csv("../Data/fasttext_dip_neighbors_orthogonal_procrustes.csv")
neural_op_report_ft = pd.read_csv("../Data/fasttext_neighbors_orthogonal_procrustes_NN.csv")

In [3]:
len(sim_mat_report_wv), len(analytical_op_report_wv), len(neural_op_report_wv), len(sim_mat_report_ft), len(analytical_op_report_ft), len(neural_op_report_ft)

(229, 635, 648, 59, 268, 274)

In [4]:
counts_data_wv = {
    'SMA': sim_mat_report_wv['Period'].value_counts(),
    'Analytical OP': analytical_op_report_wv['Period'].value_counts(),
    'Neural OP': neural_op_report_wv['Period'].value_counts()
}

In [5]:
counts_data_ft = {
    'SMA': sim_mat_report_ft['Period'].value_counts(),
    'Analytical OP': analytical_op_report_ft['Period'].value_counts(),
    'Neural OP': neural_op_report_ft['Period'].value_counts()
}

In [ ]:
df_wv = pd.DataFrame(counts_data_wv).T
df_ft = pd.DataFrame(counts_data_ft).T

df_wv.index = pd.MultiIndex.from_product([['Word2Vec'], df_wv.index], names=['Model', 'Approach'])
df_ft.index = pd.MultiIndex.from_product([['FastText'], df_ft.index], names=['Model', 'Approach'])

df_merged = pd.concat([df_wv, df_ft]).fillna(0).astype(int)

df_merged['Total'] = df_merged.sum(axis=1)

df_merged.loc[('Total', ''), :] = df_merged.sum(axis=0)

In [10]:
df_merged

Period                  13_14  13_15  13_18  13_19  13_20  14_15  14_18  \
Model    Approach
Word2Vec SMA             13.0   12.0   17.0   16.0   17.0   13.0   16.0
         Analytical OP   39.0   39.0   45.0   43.0   43.0   37.0   35.0
         Neural OP       37.0   47.0   43.0   47.0   38.0   39.0   43.0
FastText SMA              6.0    1.0    8.0    4.0    2.0    6.0    6.0
         Analytical OP   17.0   12.0   28.0   13.0   18.0   15.0   19.0
         Neural OP       16.0   19.0   18.0   12.0   14.0   18.0   19.0
Total                   128.0  130.0  159.0  135.0  132.0  128.0  138.0

Period                  14_19  14_20  15_18  15_19  15_20  18_19  18_20  \
Model    Approach
Word2Vec SMA             16.0   14.0   20.0   12.0   14.0   16.0   19.0
         Analytical OP   38.0   43.0   37.0   48.0   46.0   49.0   46.0
         Neural OP       43.0   49.0   39.0   47.0   46.0   47.0   39.0
FastText SMA              3.0    3.0    6.0    0.0    1.0    5.0    7.0
         Analytical OP   18.0   21.0   20.0   12.0   13.0   20.0   26.0
         Neural OP       19.0   22.0   21.0   19.0   15.0   20.0   21.0
Total                   137.0  152.0  143.0  138.0  135.0  157.0  158.0

Period                  19_20   Total
Model    Approach
Word2Vec SMA             14.0   229.0
         Analytical OP   47.0   635.0
         Neural OP       44.0   648.0
FastText SMA              1.0    59.0
         Analytical OP   16.0   268.0
         Neural OP       21.0   274.0
Total                   143.0  2113.0

In [8]:
df_merged.to_latex("../Data/dip_analysis_count_summary_table.tex", index=True)

In [11]:
sim_mat_report_wv.head()

,Word,Period,Similarity,Neighbors_13,Neighbors_14,Neighbors_15,Neighbors_18,Neighbors_19,Neighbors_20
0,යයි,13_14,0.0378,"අභිප්රෙතයි, විදර්ශනාවට, කාරණයෙන්, විකුර්පණය, ග...","යන්, සේ, නුවරෙක්, එක්තරා, වූයේය, කීර්ණ, ගිරිතට...",NaN,NaN,NaN,NaN
1,ආදී,13_14,0.0711,"ප්රතොලි, ශර්කරා, නගර, ව්යාහත, ප්රාකාර, උපදි, අ...","ඔහු, දත්, පූර්වයෙහි, නන්දෙඩවීම්, පැමිණියා, උපද...",NaN,NaN,NaN,NaN
2,සකල,13_14,0.0815,"චිත්තය, වාසීන්, මුළුලෝ, සම්භාවනීය, මෞදගල්යායන,...","කුලාම්බර, නෙත්රොත්සව, ගණාභරණ, සත්ත්ව, දෙහ, රස්...",NaN,NaN,NaN,NaN
3,කර්ම,13_14,0.0945,"කෙශයෙහි, කාය, ස්ථාන, ථාවරය, ගන්ධය, චර්මානන්තරග...","සක්දෙව්, විශ්ව, අඳුන්, දිවිසම්, නියොග, ලත්, ශා...",NaN,NaN,NaN,NaN
4,සහිත,13_14,0.1191,"ඵලගූ, උපසපනුන්, ඉහි, ග්රහණ, ප්රකාශ, මේලෙසින්, ...","වාකචීරාදීන්, තිබූ, ක්ෂීණාශ්රවයන්, දිවිසම්, සන්...",NaN,NaN,NaN,NaN

In [14]:
sim_mat_report_wv['Word'].value_counts()

Word
සේ           11
සියලු         9
මෙසේ          8
පරිද්දෙන්     7
හා            7
ක්රමයෙන්      6
වනාහි         6
හෙයින්        6
එයින්         6
හි            5
බැවින්        5
යුක්ත         5
නැති          5
පටන්          5
සහිත          5
කල්හි         4
යෙහි          4
හෝ            4
නොයෙක්        4
වන්නේ         4
වට            4
ඇත්තේ         4
මෙහි          4
හට            4
ගෙණ           4
ආදී           3
උතුම්         3
සමග           3
එම            3
තවද           3
පුරුෂ         3
මතු           3
එසේම          3
දෙක           3
යයි           3
ඒ             2
කළ            2
සියල්ල        2
රන්           2
පිට           2
යට            2
වෙන           2
සම්පුර්ණ      2
සකල           2
කර්ම          2
නමැති         2
සඳහා          2
අග්ර          2
සංඛ්යාත       2
තල            2
සර්ව          2
අක්ෂර         1
ගේ            1
ප්රථම         1
කිසි          1
සම්පූර්ණ      1
මෙන්          1
චන්ද්රයා      1
පංච           1
ඇති           1
බුදුන්        1
කුමක්         1
නිසි          1
බුද්ධ         1
යනාදී         1
උපන්          1
අර්ථ          1
පාද           1
සත්ව          1
එසේ           1
නැ            1
සුදුසු        1
ගුණ           1
ගත            1
ප්රීති        1
මල            1
හෙවත්         1
කෙරෙන්        1
බවට           1
සැප           1
දක්වා         1
යම්           1
Name: count, dtype: int64

In [19]:
analytical_op_report_ft['Word'].value_counts()

Word
පිට          15
පුර          12
අග්ර          9
නම්           8
මෙහි          8
හෙයින්        8
දෙන           7
මාර්ග         6
එයින්         6
සියල්ල        6
අර්ථ          6
දිව්ය         5
කෙනෙක්        5
අවුත්         5
සර්ව          5
යුතුයි        5
කරුණාවෙන්     5
පංච           5
පිණිස         5
බ්රහ්ම        4
හෙවත්         4
ඇත්තේ         4
සසර           4
තමන්ගේ        4
මතු           4
සතර           4
සඳහා          4
මාගේ          4
කරණ           4
ගත්           4
කියන          4
විසින්        3
මෙන්          3
ඇති           3
අතුරෙන්       3
දන්නා         3
වහන්සේ        3
වන්නේය        3
කටයුතු        3
අක්ෂර         3
වන්නේ         3
අසා           3
යනු           3
සිටි          2
මල්           2
පරිද්දෙන්     2
පස්           2
පාද           2
වනාහි         2
ලද්දා         2
සියලු         2
චන්ද්රයා      2
කිසි          2
එසේම          2
යනාදීන්       2
රාජ           2
යයි           2
දත්           2
බැවින්        2
දක්වා         2
නැති          1
මහත්          1
නොව           1
සැප           1
බුදු          1
පවත්වන        1
දැක           1
කෙරෙහි        1
ගන්නා         1
නැවත          1
නොයෙක්        1
කරණු          1
සර්වඥ         1
වීම           1
සිට           1
කල්ප          1
ප්රධාන        1
වන            1
ඔහු           1
Name: count, dtype: int64

In [54]:
analytical_op_report_ft[analytical_op_report_ft['Word'] == 'මල්']

,Word,Period,Similarity,Neighbors_13,Neighbors_14,Neighbors_15,Neighbors_18,Neighbors_19,Neighbors_20
224,මල්,18_19,0.7712,NaN,NaN,NaN,"අනා, වැඳ, වෙස්සභූ, ජාතීන්, වර්ණයා, සිරි, දර්ශ, දත්, සිනා, ලක්ෂණ","ගෙදර, විලසට, ලියමන, මෙසේත්, වඳිම්, දෙක්හි, බැස, ඇත්තක්, ගිහි, වශයෙන්ම",NaN
256,මල්,19_20,0.7857,NaN,NaN,NaN,NaN,"ගෙදර, විලසට, ලියමන, මෙසේත්, වඳිම්, දෙක්හි, බැස, ඇත්තක්, ගිහි, වශයෙන්ම","විනය, කිරුලට, චන්ද, පන්දාස්, ස්ථානය, සංඝයා, උරෙන්, වෙසක්, විහාර, මධ්ය"

In [55]:
neural_op_report_wv[neural_op_report_wv['Word'] == 'මල්']

,Word,Period,Similarity,Neighbors_13,Neighbors_14,Neighbors_15,Neighbors_18,Neighbors_19,Neighbors_20
26,මල්,13_14,0.4909,"බොධිසම්භාර, කප්රුක, පල්ලව, අමාඵල, ගන්වයි, චර්යයා, අතුපතර, බුදුවෙයි, ලියයෙකින්, මෙත්","වදාරන්නේ, පසඟ, ගැත්තවුන්, දවසට, බන, පුදා, සරහන්නා, ඉවසා, සෙට, අත්",NaN,NaN,NaN,NaN
243,මල්,14_15,0.3856,NaN,"වදාරන්නේ, පසඟ, ගැත්තවුන්, දවසට, බන, පුදා, සරහන්නා, ඉවසා, සෙට, අත්","භාෂාවෙන්, කැලියනු, සංසකෘත, හෝ, ප්රකෘතියෙකි, කැකුලට, පර්ය්යා, තද්භව, කලි, ශබ්ද",NaN,NaN,NaN
258,මල්,14_18,0.3630,NaN,"වදාරන්නේ, පසඟ, ගැත්තවුන්, දවසට, බන, පුදා, සරහන්නා, ඉවසා, සෙට, අත්",NaN,"කිණිහිරි, දහවත්තරු, බෙරලිය, සුදු, වුවමනාතන්හි, කළු, භාණි, රුක්, පෙනල, පැහැය",NaN,NaN
325,මල්,14_19,0.3607,NaN,"වදාරන්නේ, පසඟ, ගැත්තවුන්, දවසට, බන, පුදා, සරහන්නා, ඉවසා, සෙට, අත්",NaN,NaN,"සඳුට, පුදමි, මුණින්ද්රයාට, මිතුරාට, ලොවට, තිලොවට, දෙවරුපු, පුෂ්පයන්, සිදුරු, සිංහපුරයෙහි",NaN
377,මල්,14_20,0.3787,NaN,"වදාරන්නේ, පසඟ, ගැත්තවුන්, දවසට, බන, පුදා, සරහන්නා, ඉවසා, සෙට, අත්",NaN,NaN,NaN,"පල, තුරූ, තුරුවත්, පානෙම්, සසිරි, වෙසෙසෙකි, පිපෙන්නා, පිපෙන, විතර, ගහේ"
556,මල්,18_19,0.4290,NaN,NaN,NaN,"කිණිහිරි, දහවත්තරු, බෙරලිය, සුදු, වුවමනාතන්හි, කළු, භාණි, රුක්, පෙනල, පැහැය","සඳුට, පුදමි, මුණින්ද්රයාට, මිතුරාට, ලොවට, තිලොවට, දෙවරුපු, පුෂ්පයන්, සිදුරු, සිංහපුරයෙහි",NaN